"use client"
import Navbar from '@/components/Navbar';
import '../app/globals.css';
import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from '@/components/ui/toaster';
import Provider from '@/components/provider';
import Footer from '@/components/Footer';
import NProgress from 'nprogress';
import { usePathname, useRouter } from 'next/navigation';
import { useEffect } from 'react';

const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }) {
  // NProgress.start();
  const pathname = usePathname();
  const router = useRouter();
  useEffect(() => {
    // router.events.on('routeChangeStart', () => {
    //   NProgress.start();
    // });
    // router.events.on('routeChangeComplete', () => {
    //   NProgress.done();
    // });
    // router.events.on('routeChangeError', () => {
    //   NProgress.done();
    // });
    NProgress.start();
    setTimeout(()=>{
      NProgress.done();
    }, 2000)
  }, [pathname]);
  return (
    <html lang='en'>
      <body >
        <Provider>
          <main className=''>
            <div className=''>
              {/* <Navbar /> */}
                {children}
              {/* <Footer/> */}
            </div>
          </main>
          <Toaster/>
        </Provider>
      </body>
    </html>
    // className={inter.className}
  );
}
